# Generated by Django 4.1.2 on 2023-02-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='people',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
